### ISSUE TITLE
"BuildArch: noarch" results in subsequent packages to become "Architecture: all"

### ISSUE THREAD

**Issue by AEI-SXSmirror** [macq/spec2deb#5]
If in the spec file there are subpackages declared as "BuildArch: noarch" (arch-independent), all subsequent packages _without_ a "BuildArch" line get "Architecture: all" assigned as well - should be "Architecture: any" to mark binary arch-dependency.

Apparently the setting is not cleared when proceeding from one %package entry to the next.

**Comment by chrismaes87** [comment]
A fix has been implemented. Please use the latest version.
